### ISSUE TITLE
issue with maven (as Eclipse Pug-in)

### ISSUE THREAD

**Issue by ghost** [teigen/maven-scalatest-plugin#1]
in file maven-scalatest-plugin/src/it/scalatestexamples/pom.xml
   line 12
   id contains a '/'
Eclipse returns:
"04/12/09 08:06:51 GMT: [WARN] repository metadata for: 'snapshot org.scalatest:scalatest:1.0-SNAPSHOT' could not be retrieved from repository: scala-tools.org / snapshots due to an error: GET request of: org/scalatest/scalatest/1.0-SNAPSHOT/maven-metadata.xml from scala-tools.org / snapshots failed"

Fix change the / with a -

I can't find a way to make this issue minor/trivial but it may put of newbye.

**Comment by teigen** [comment]
fixed
