### ISSUE TITLE
how to test continously?

### ISSUE THREAD

**Issue by mgutz** [teigen/maven-scalatest-plugin#3]
Awesome plugin. I'm new to Maven and I haven't seen anything on google on how to do continuous testing with this plugin? When I run `mvn scala:cctest` it does not detect any specs. Is there a way to do this?

**Comment by teigen** [comment]
I haven't tried it myself, but according to https://github.com/davidB/maven-scala-plugin/blob/master/src/main/java/org_scala_tools_maven/ScalaContinuousTestMojo.java it should work.

Try running mvn -Dcctest.goals="scalatest:test" scala:cctest
and see if it works.

**Comment by mgutz** [comment]
Thank you, that worked with 2.15.1-SNAPSHOT
